---
book_repo: pivotal-cf/docs-book-addon-fim
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: master

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:
  # cross-product resources
- repository:
    name: pivotal-cf/docs-partials
    ref: main
  directory: fim/partials
  no_docs: true

- repository:
    name: pivotal-cf/docs-addon-fim
    ref: 'v1.3'
  directory: addon-fim/1-3
  subnav_template: addon_fim_1-3.erb
  product_info:
    use_local_header: true
    latest_stable_version: 2.1
    changelog_href: https://docs.pivotal.io/addon-fim/1-3/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: FIM Add-on for PCF
    search_placeholder: Search Fim Add-on for PCF 1.3
    url_prefix: addon-fim/1-3
    local_product_version: '1.3'
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/addon-fim/2-1
        display_name: 2.1
      - url_prefix: http://docs.pivotal.io/addon-fim/2-0
        display_name: 2.0
      - url_prefix: http://docs.pivotal.io/addon-fim/1-4
        display_name: 1.4
      - url_prefix: http://docs.pivotal.io/addon-fim/1-2
        display_name: 1.2
