---
book_repo: pivotal-cf/docs-book-addon-fim
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: edge

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:
# cross-product resources
- repository:
    name: pivotal-cf/docs-partials
    ref: master
  directory: fim/partials
  no_docs: true

- repository:
    name: pivotal-cf/docs-addon-fim
    ref: 'master'
  directory: addon-fim/1-n
  subnav_template: addon_fim_1-n.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.3
    changelog_href: https://docs.pivotal.io/addon-fim/1-n/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: File Integrity Monitoring Add-on for PCF
    search_placeholder: Search Fim Add-on for PCF 1.4
    url_prefix: addon-fim/1-n
    local_product_version: 1.4
    local_header_links: []
    local_header_version_list: []
